
family = "samples-untouchedsvgz"
output_file = "samples-untouchedsvgz.ttf"
color_format = "untouchedsvgz"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = ["renamed_samples/67-72-61-64-69-65-6e-74-5f-73-74-6f-70-5f-6f-70-61-63-69-74-79.svg", "renamed_samples/6c-69-6e-65-61-72-5f-72-65-66-6c-65-63-74.svg", "renamed_samples/6c-69-6e-65-61-72-5f-72-65-70-65-61-74.svg", "renamed_samples/6c-69-6e-65-61-72-5f-74-72-61-6e-73-66-6f-72-6d.svg", "renamed_samples/72-61-64-69-61-6c-5f-72-65-66-6c-65-63-74.svg", "renamed_samples/72-61-64-69-61-6c-5f-72-65-70-65-61-74.svg", "renamed_samples/72-61-64-69-61-6c-5f-74-72-61-6e-73-66-6f-72-6d.svg", "renamed_samples/73-69-6d-70-6c-65-5f-6c-69-6e-65-61-72.svg", "renamed_samples/73-69-6d-70-6c-65-5f-72-61-64-69-61-6c.svg"]

[master.regular.position]
wght = 400
